#deployments vem de apps/v1
 apiVersion: apps/v1
 #tipo
 kind: Deployment
 metadata:
 #nome do deployment
   name: arsenal-deployment
 spec:
  #quantas cópias
  replicas: 1
  #para especificar o rótulo
  selector:
   matchLabels:
    #rótulo, app não tem nada de especial, pode ser qq coisa
    #Deployment vai selecionar todo Pod que tiver esse rótulo
    app: arsenal
  #modelo que vai ser usado para construção dos Pods
  template:
    metadata:
      labels:
      #os Pods terão esse rótulo, assim,
      #serão selecionados por esse deployment
        app:arsenal
    spec:
      containers:
        - name: arsenal
          image: gabrielgarofalo/arsenal:0.0.1
      resources:
        limits:
          memory: 256Mi
          cpu: 1
apiVersion: v1
kind: Service
metadata:
  name: arsenal-clusterip-service
spec:
  selector:
    app: arsenal
  ports:
    name: arsenal
    protocol: TCP
    port: 3000
    targetPort: 3000
